INSERT INTO TB_USERS (NAME, CITY, STATE, ZIP, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('Ethan', 'Plymouth', 'MI', '48170', false, false, false);
INSERT INTO TB_USERS (NAME, CITY, STATE, ZIP, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('Madisyn', 'Plymouth', 'MI', '48170', true, true, true);
INSERT INTO TB_USERS (NAME, CITY, STATE, ZIP, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('Steve', 'Westland', 'MI', '48185', false, false, false);

INSERT INTO TB_RESTAURANTS (NAME, ZIPCODE) VALUES ('Bronx Pizza', '48170');
INSERT INTO TB_RESTAURANTS (NAME, ZIPCODE) VALUES ('E.G. Nicks', '48170');
INSERT INTO TB_RESTAURANTS (NAME, ZIPCODE) VALUES ('Taco Bell', '48185');

INSERT INTO TB_DINING_REVIEWS (SUBMITTED_BY, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, STATUS) VALUES ('Ethan', 1, 2, 3, 5, 'PENDING');
INSERT INTO TB_DINING_REVIEWS (SUBMITTED_BY, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, STATUS) VALUES ('Madisyn', 1, 5, 3, 1, 'PENDING');
INSERT INTO TB_DINING_REVIEWS (SUBMITTED_BY, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, STATUS) VALUES ('Steve', 3, 5, 3, 5, 'PENDING');