INSERT INTO TB_USERS (ID, NAME, CITY, STATE, ZIP, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES (1, 'Ethan', 'Plymouth', 'MI', '48170', false, false, false);
INSERT INTO TB_USERS (ID, NAME, CITY, STATE, ZIP, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES (2, 'Madisyn', 'Plymouth', 'MI', '48170', true, true, true);
INSERT INTO TB_USERS (ID, NAME, CITY, STATE, ZIP, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES (3, 'Steve', 'Westland', 'MI', '48185', false, false, false);

INSERT INTO TB_RESTAURANTS (ID, NAME, ZIPCODE) VALUES (1, 'Bronx Pizza', '48170');
INSERT INTO TB_RESTAURANTS (ID, NAME, ZIPCODE) VALUES (2, 'E.G. Nicks', '48170');
INSERT INTO TB_RESTAURANTS (ID, NAME, ZIPCODE) VALUES (3, 'Taco Bell', '48185');

INSERT INTO TB_DINING_REVIEWS (ID, SUBMITTED_BY, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, STATUS) VALUES (1, 'Ethan', 1, 2, 3, 5, 'PENDING');
INSERT INTO TB_DINING_REVIEWS (ID, SUBMITTED_BY, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, STATUS) VALUES (2, 'Madisyn', 1, 5, 3, 1, 'PENDING');
INSERT INTO TB_DINING_REVIEWS (ID, SUBMITTED_BY, RESTAURANT_ID, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, STATUS) VALUES (3, 'Steve', 3, 5, 3, 5, 'PENDING');